### ISSUE TITLE
Deployment broken 

### ISSUE THREAD

**Issue by kDipak** [avdbrink/VSTS-SSAS-Extension#2]
Hey Arno, 

Kerel, leuke script 👍 Wij gebruiken het al een tijdje maar de laatste release heeft alles kapot gemaakt :) 

this has to do with the new feature that was added, which does not pass on Tabular models.

here are screenshots with the errors, we also noticed that it deploys the cubes but errors out on this last step.

![image](https://user-images.githubusercontent.com/10881222/53735281-b97c9480-3e86-11e9-951e-6498a417d32b.png)

![image](https://user-images.githubusercontent.com/10881222/53735017-f1cfa300-3e85-11e9-8960-8a7e6e8b4d51.png)

2019-03-04T13:05:46.7548809Z ##[section]Starting: Deploy SSAS Hours
2019-03-04T13:05:46.7554307Z ==============================================================================
2019-03-04T13:05:46.7554386Z Task         : SSAS Deploy
2019-03-04T13:05:46.7554446Z Description  : Deploy SQL Server Analysis Services Project .xmla file using Invoke-ASCmd
2019-03-04T13:05:46.7554519Z Version      : 0.4.7
2019-03-04T13:05:46.7554569Z Author       : avbrink
2019-03-04T13:05:46.7554785Z Help         : 
2019-03-04T13:05:46.7554839Z ==============================================================================
2019-03-04T13:05:47.8694158Z ==============================================================================
2019-03-04T13:05:47.8694413Z Starting DeploySSASTask
2019-03-04T13:05:47.9041884Z Asdatabase file path: C:\vstsagent\A1\_work\r3\a\_B_IFS - AS\SSAS_Release\TAB - Hours\bin\Release\Model.asdatabase
2019-03-04T13:05:47.9115630Z Deployment executable version: C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe
2019-03-04T13:05:49.1746744Z Creating .xmla file from .asdatabase...
2019-03-04T13:05:49.2973123Z Reading input files...
2019-03-04T13:05:49.5474991Z Done
2019-03-04T13:05:50.1820688Z Connecting to the TAB server
2019-03-04T13:05:50.1891885Z Database, Hours, found on server, \TAB. Applying configuration settings and options...
2019-03-04T13:05:50.1941146Z 	Analyzing configuration settings...
2019-03-04T13:05:50.1941380Z 	Done
2019-03-04T13:05:50.1941493Z 	Analyzing storage information...
2019-03-04T13:05:50.1941618Z 	Done
2019-03-04T13:05:50.1941731Z 	Analyzing security information...
2019-03-04T13:05:50.1942001Z 		Analyzing permissions...
2019-03-04T13:05:50.1942315Z 		Company Role
2019-03-04T13:05:50.1942411Z 		Done
2019-03-04T13:05:50.1942503Z 	Done
2019-03-04T13:05:50.1942828Z Generating processing sequence...
2019-03-04T13:05:50.1942956Z Saving deployment script to C:\vstsagent\A1\_work\r3\a\_B_IFS - AS\SSAS_Release\TAB - Hours\bin\Release\Model.xmla
2019-03-04T13:05:50.1943245Z Done
2019-03-04T13:05:50.1992575Z Deploying  database ...
2019-03-04T13:05:50.9742335Z Changing impersonation info from ImpersonateServiceAccount to ImpersonateCurrentUser on datasource MML
2019-03-04T13:05:51.1352198Z ##[error]Task_InternalError The following exception occurred while retrieving member "SaveChanges": "Encountered an invalid type for a default value."
2019-03-04T13:05:51.1923693Z ##[section]Finishing: Deploy SSAS Hours

**Comment by avdbrink** [comment]
Hi Dipak,

Glad to hear you like the component. But sorry to hear the new release has broken your deployment. ;-)

What I can make of the error is that it seems impossible to save the impersonation options. It changes them from Service account to Current user. 
I’ve tested such a change and could not reproduce the error. What are the settings of the MML datasource? Is it a SQL Server database connection? 
And are there any specific settings you use in your project?

**Comment by kDipak** [comment]
The MML connection is very straightforward.

![image](https://user-images.githubusercontent.com/10881222/53890406-7528fa00-4028-11e9-8828-ace2baecbe21.png)

![image](https://user-images.githubusercontent.com/10881222/53890498-9ee22100-4028-11e9-9441-ec279c493932.png)

In the project the Impersonation setting is always on Service Account. in DevOps I tried all the settings and no matter what i select it always fails on this step, even with it set to inherit it still tries to do something and fails.

inherit:
![image](https://user-images.githubusercontent.com/10881222/53894186-f46dfc00-402f-11e9-84b2-9db8944feb24.png)

self to self ?
![image](https://user-images.githubusercontent.com/10881222/53894204-fcc63700-402f-11e9-9c66-415034ec881c.png)

UserAccount to Current user
![image](https://user-images.githubusercontent.com/10881222/53894248-123b6100-4030-11e9-9854-9fd4eb081405.png)

**Comment by erindru** [comment]
We are also experiencing this issue and have not been able to deploy any cubes since the update. Is there a way to roll back to an older version? We are using Microsoft-hosted Azure DevOps

**Comment by avdbrink** [comment]
I’m looking into the cause but cannot find it. Meanwhile I found another way to set the impersonation even before the tabular gets deployed to the server. This should prevent the error from happening at all.
I’m going to build this into the component and test it. I will not be able to test it before tomorrow, but I’ll let you know as soon as the results are in.

**Comment by kDipak** [comment]
I wrote a deployment script that sets all the properties in the .asdatabase file, and then generate the XMLA based on the edited .asdatabase.

**Comment by avdbrink** [comment]
Hi,
I've done exactly the same :)
The component on Microsoft Marketplace is now updated, as is the github repository (1.0.1 is the latest version)
Since the credentials are not updated after deployement the error should not occur again, but I'd like to hear confirmation of you if this version is working for you.

**Comment by kDipak** [comment]
If i get the chance i will test it, in the meantime i wrote a script that deploys all cubes in our solution in 1 batch.

thanks for the help.

**Comment by erindru** [comment]
Thanks - it's improved, but not quite working yet. I think i've entered DLL hell that may be specific to our environment.

1. We were using the 'SSAS Deploy' task within a custom Task Group - I edited the Task Group and changed the version of the 'SSAS Deploy' task from '0.x' to '1.x'
2. I was getting a `Could not load file or assembly 'Microsoft.AnalysisServices.AppLocal.Tabular.Json, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.` error - and I couldnt figure out why it was looking for an 'AppLocal' assembly when nothing with that name existed. Eventually I figured out that I needed to update the SqlServer PowerShell module by executing `Update-Module -Name SqlServer` in an Admin PowerShell - which updated the PowerShell module to `21.1.18080`

However - that's where i'm now stuck. The script aborts when it tries to call `[Microsoft.AnalysisServices.Tabular.JsonSerializer]::DeserializeDatabase` with the following error:

```
2019-03-11T20:46:14.6130168Z ##[error]Task_InternalError Exception calling "DeserializeDatabase" with "1" argument(s): "Could not load file or assembly 'Microsoft.AnalysisServices.Tabular.Json, Version=15.12.3.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified."
```

I attempted to recreate the situation in a PowerShell window. I notice that the script runs

```powershell
Import-Module SqlServer
```

which pulls in a bunch of Analysis Services dependencies, and then calls 

```powershell
[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices")
```

to presumably pull in the rest of the Analysis Services DLLS.
So I ran these to import the assemblies into the current PowerShell context.

I then ran:

```powershell
[AppDomain]::CurrentDomain.GetAssemblies() | sort -property FullName | Format-Table FullName
```

to check the versions that were loaded. It showed that `Microsoft.AnalysisServices, Version=15.12.3.0` was loaded. However, callling `[Microsoft.AnalysisServices.Tabular.JsonSerializer]::DeserializeDatabase("")` resulted in the same assembly error. I then tried to load the assembly manually, via:

```powershell
[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices.Tabular.Json")
```

which loaded version `14.0.0.0` from the GAC (which presumably was installed when SSMS was installed). Clearly this version was too old as the error indicated it was expecting version `15.12.3.0`, so I installed the [AMO and AMOMD](https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers) libraries from Microsoft. This improved things slightly - version `15.0.0.0` showed as being loaded when manually loading the "Microsoft.AnalysisServices.Tabular.Json" namespace. However, the same error persisted - it was still looking for version `15.12.3.0` which I cannot for the life of me figure out how to load.

Any suggestions?

**Comment by erindru** [comment]
I also tried downgrading the SqlServer PS module back to version `21.1.18068` which started looking for the `15.0.0.0` versions of the assemblies again (as opposed to the `15.12.3.0` versions). I then reinstalled the [AMO library](https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers) since it had version `15.0.0.0` of the JSON assembly.

However - for some dumb reason, version `21.1.18068` looks for assemblies in an "AppLocal" namespace which can't find the JsonSerializer class.

@avdbrink What version of the `SqlServer` module are you using for development?

**Comment by avdbrink** [comment]
Hi erindru,
I've not really had time to look into this, but to answer your question: after a run of LoadWithPartialName("Microsoft.AnalysisServices") and running "Import-Module SqlServer" I see the following assemblies loaded (regarding SQL server):

Microsoft.AnalysisServices, Version=13.0.0.0                          
Microsoft.AnalysisServices, Version=14.0.0.0                          
Microsoft.AnalysisServices.Core, Version=13.0.0.0                     
Microsoft.AnalysisServices.PowerShell.Cmdlets, Version=13.0.0.0       
Microsoft.AnalysisServices.PowerShell.Provider, Version=13.0.0.0      
Microsoft.AnalysisServices.Tabular, Version=13.0.0.0                  
Microsoft.AnalysisServices.Tabular.Json, Version=14.0.0.0             
Microsoft.SqlServer.ConnectionInfo, Version=13.0.0.0                  
Microsoft.SqlServer.Dmf, Version=13.0.0.0                             
Microsoft.SqlServer.Management.AlwaysEncrypted.Types, Version=13.0.0.0
Microsoft.SqlServer.Management.Collector, Version=13.0.0.0            
Microsoft.SqlServer.Management.CollectorEnum, Version=13.0.0.0        
Microsoft.SqlServer.Management.HadrDMF, Version=13.0.0.0              
Microsoft.SqlServer.Management.PSProvider, Version=13.0.0.0           
Microsoft.SqlServer.Management.PSSnapins, Version=13.0.0.0            
Microsoft.SqlServer.Management.RegisteredServers, Version=13.0.0.0    
Microsoft.SqlServer.Management.Sdk.Sfc, Version=13.0.0.0              
Microsoft.SqlServer.Management.Utility, Version=13.0.0.0              
Microsoft.SqlServer.Management.UtilityEnum, Version=13.0.0.0          
Microsoft.SqlServer.RegSvrEnum, Version=13.0.0.0                      
Microsoft.SqlServer.ServiceBrokerEnum, Version=13.0.0.0               
Microsoft.SqlServer.Smo, Version=13.0.0.0                             
Microsoft.SqlServer.SmoExtended, Version=13.0.0.0                     
Microsoft.SqlServer.SqlEnum, Version=13.0.0.0                         
Microsoft.SqlServer.SqlWmiManagement, Version=13.0.0.0                
Microsoft.SqlServer.WmiEnum, Version=13.0.0.0  

So there's both a 13.0.0.0 and a 14.0.0.0 version of AnalysisServices.

When I run [System.Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices") in a clean powershell it seems to load the 14.0.0.0 version. When I run Import-Module SqlServer the rest of the assemblies (the 13.0.0.0 versions) appear. When I only try to load the Tabular.Json assembly it also loads the 14.0.0.0  version.
The version of management studio I have installed on the build agent is 13.0.16106.4 (SSMS 2016)

Hope this helps you in finding out what's going on on your side.

I've thought of a solution to fix this whole issue. It is not something I prefer, but what might be working: I could make an option in the component to skip the impersonation altogether. Than none of the assemblies will be loaded, so no error can occur :) Let me know if that would work for you.

**Comment by erindru** [comment]
I see - your environment has much older versions of the assemblies in it. We are deploying to a SQL Server 2016 instance but our build environment has SSMS 17.9.1 and the latest version of the SqlServer PowerShell module (which appears to bundle its own version of the AnalysisServices dependencies, however omits the Tabular.Json assembly for some reason) as well as I have been experimenting with installing AMO to see if that made a difference.

In actual fact you're right - disabling impersonation altogether might work for us. In fact my colleague (who originally brought this issue to my attention) suggested as much - we apparently don't need it in our environment, and he was surprised that an option to disable it was not present in the UI.

**Comment by avdbrink** [comment]
I've just uploaded a new release of the component to the Microsoft Marketplace and created a release right [here](https://github.com/avdbrink/VSTS-SSAS-Extension/releases/latest) on Github. Only change is the addition of an option to skip impersonation at all.

**Comment by erindru** [comment]
Thanks @avdbrink - the option to disable impersonation fixed the issue for us. It's all working again!
