### ISSUE TITLE
##[error]Task_InternalError Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by alwortman** [avdbrink/VSTS-SSAS-Extension#3]
Hi,

I'm seeing an issue when trying to deploy a tabular model.

![image](https://user-images.githubusercontent.com/13524879/54631158-a77b2400-4a38-11e9-9cc0-f1e342ff9036.png)

When I create a manual Powershell script task and run this line:

Test-Path D:\a\r1\a\_Pandora\Builds\Release\Model.asdatabase

It returns "True" and completes the task successfully.

![image](https://user-images.githubusercontent.com/13524879/54631221-c8437980-4a38-11e9-8e2c-c663da7b72e0.png)

Looking at the code I thought that might be happening at this line:

![image](https://user-images.githubusercontent.com/13524879/54631351-12c4f600-4a39-11e9-84f3-53c7b720c0b8.png)

Thanks for taking look at this. This utility is awesome!

-Edit: I forgot to mention this was using a hosted agent

**Comment by avdbrink** [comment]
Hi,
I think you're right about the location where the error occurs. The [io.path]::GetFileNameWithoutExtension might be the issue.
Could you try to run this line from a powershell session on you're hosted agent?
Something like: 
PS > [io.path]::GetFileNameWithoutExtension("D:\a\r1\a_Pandora\Builds\Release\Model.asdatabase")

On my agent this returns
Model
My assumption is that the first line doesn't give any error, but testing could do no harm:
PS > Split-Path -Path "Split-Path -Path "D:\a\r1\a_Pandora\Builds\Release\Model.asdatabase"\Model.asdatabase"
Should return: 
D:\a\r1\a_Pandora\Builds\Release

If you post the results of these tests here I'll try to look into it.

**Comment by avdbrink** [comment]
By the way: you mention you're using a hosted agent, but is this a Microsoft-hosted agent or a Self-hosted agent?

**Comment by alwortman** [comment]
This was on a Microsoft-hosted agent.

I created a Powershell task with this code:
```
$AsDBFilePath = $args[0]

$path = Split-Path -Path $AsDBFilePath
$modelName = [io.path]::GetFileNameWithoutExtension($AsDBFilePath)

Write-Output $path
Write-Output $modelName
```
And passed this as the argument:

![image](https://user-images.githubusercontent.com/13524879/54715990-f5b02600-4b11-11e9-8052-40e78d47716b.png)

The output matches what you thought it should:

```
2019-03-20T20:09:42.7690672Z ##[section]Starting: PowerShell Script copy
2019-03-20T20:09:42.7752848Z ==============================================================================
2019-03-20T20:09:42.7753539Z Task         : PowerShell
2019-03-20T20:09:42.7753664Z Description  : Run a PowerShell script on Windows, macOS, or Linux.
2019-03-20T20:09:42.7753743Z Version      : 2.148.0
2019-03-20T20:09:42.7753812Z Author       : Microsoft Corporation
2019-03-20T20:09:42.7753895Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2019-03-20T20:09:42.7753968Z ==============================================================================
2019-03-20T20:09:43.8954871Z Generating script.
2019-03-20T20:09:43.9041626Z Formatted command: . 'D:\a\r1\a\_Pandora\Scripts\release_test2.ps1' D:\a\r1\a/_Pandora/Builds/Release/Model.asdatabase
2019-03-20T20:09:43.9774080Z ========================== Starting Command Output ===========================
2019-03-20T20:09:44.0102749Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\aea623b8-e0d1-4b8d-9fe0-0e1827d07679.ps1'"
2019-03-20T20:09:44.7515047Z D:\a\r1\a\_Pandora\Builds\Release
2019-03-20T20:09:44.7517915Z Model
2019-03-20T20:09:44.8020955Z ##[section]Finishing: PowerShell Script copy
```

**Comment by GaborVroegop** [comment]
Nice debugging!
Same result here with a powershell script - self hosted agent (on premise servers). Path and file name are returned as expected.

**Comment by alwortman** [comment]
So I did some more digging and now I believe this is due to the location of Microsoft.AnalysisServices.Deployment.exe file on Microsoft-hosted agents. As far as I can tell all Microsoft-hosted agents have D:/ as their root directory.

When I ran DeploySSASTask.ps1 on a local machine I got past the step that had thrown the error originally

```
Asdatabase file path: C:\agent\_work\r1\a\_Pandora\Builds\Release\Model.asdatabase
...
Deployment executable version: C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe
...
```

I then realized that if none of the specified file paths are present the $compiler variable will not get set (and thus be null).

```
	switch ($mgmtVersion) 
	{ 
		2012 {$compiler = "C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"} 
		2014 {$compiler = "C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
		2016 {$compiler = "C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
		2017 {$compiler = "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
		"auto" {
			if (Test-Path("C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe")) { $compiler = "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
			if (Test-Path("C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe")) { $compiler = "C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
			if (Test-Path("C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe")) { $compiler = "C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
			if (Test-Path("C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe")) { $compiler = "C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"}
		}
	}
```

Edit: Aaaand here is the issue.

https://github.com/Microsoft/azure-pipelines-image-generation/issues/105

It looks like it's not supported yet.

**Comment by avdbrink** [comment]
I was on the same track.

I thought I had a workaround for this by using an older Agent (the 2015 Agent) but it doesn't seem like this version has the analysis deployment wizard as well.

I think the only option to overcome this is using a self-hosted agent :(

**Comment by GaborVroegop** [comment]
We deploy with Azure DevOps pipelines to on-premise SQL Servers (so self hosted agents and not Microsoft hosted agents).

The deployment wizard is installed on the D (application) drive on all servers and in our case $compiler is also empty. When I manually set the compiler to the correct path in the file DeploySSASTask.ps1 it runs succesful:
$compiler = "D:\MSSQL`$MSSQL\x86\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"
Does anybody have an idea how to make the reference to the deployment wizard dynamic?

**Comment by avdbrink** [comment]
I could add an option to use a user defined compiler, in which case you could enter the above location when configuring your release. The standard location of the component is "C:\Program Files (x86)\Microsoft SQL Server\XXX\Tools\Binn\ManagementStudio" so that's why your agent is unable to find the compiler.

**Comment by GaborVroegop** [comment]
That would be a nice option, then we can set it with a variable.

**Comment by alwortman** [comment]
I _think_ that might be enough to solve my issue as well. In theory you might be able to just include a copy of the Microsoft.AnalysisServices.Deployment.exe file in your source control and reference that when running the task on a MS hosted agent.

**Comment by avdbrink** [comment]
I don’t think including only the executable would do the trick. You need a complete ssms installation or at least some more dll’s to get this to work. I’ll update the code to make the location of the executable a variable so at least when you run a self-hosted agent you can specify the location. This will be somewhere next week though.

**Comment by avdbrink** [comment]
Component is in the Visual Studio Marketplace with the new option! Version 1.0.6
Please let me know if this fixes your issues :)

**Comment by GaborVroegop** [comment]
Thx, as soon as the update is available in our  project I will test it and let you know (will be updated automatically according to our administrator).

**Comment by GaborVroegop** [comment]
Hi Arno,

Works like a charm, thx for the fix!

Regards,
Gabor

**Comment by alwortman** [comment]
I was finally able to get this working on a locally hosted agent (which uses the default installation path). The custom executable location is a nice add though :) . As far as MS-hosted agents, that would require them to install the deployment executables on their side, which they haven't done yet. 

I think we can mark this one as closed. Thanks for all the help!

**Comment by avdbrink** [comment]
Thanks for testing guys, I'll close the issue now.
